[package]
name = "cpp-amalgamate"
version = "0.1.0"
authors = ["David Stangl <david.stangl@student.hpi.de>"]
edition = "2021"
rust-version = "1.56"
resolver = "2"

[dependencies]
anyhow = "1.0.44"
bstr = "0.2.17"
globset = "0.4.8"
itertools = "0.10.1"
log = { version = "0.4.14", features = ["std"] }
regex = "1.5.4"
structopt = "0.3.25"
termcolor = "1.1.2"

[dev-dependencies]
tempfile = "3.2.0"
